name: Test python App

on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Coverage testing 
      run: | 
        coverage run manage.py test -v 2
        coverage report
        coverage xml
    - uses: actions/upload-artifact@v2
      with:
        name: coverage.xml
        path: coverage.xml
  sonarcloud:
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get coverage.xml
      uses: actions/download-artifact@v2
      with:
        name: coverage.xml
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  check_result_test:
    needs: testing
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Failed tests
      if: ${{ needs.testing.result == 'failure' }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: backend
        SLACK_COLOR: "#9e2a2b"
        #SLACK_ICON: https://someurl.com/logo.png
        SLACK_MESSAGE: "backend test failed"
        SLACK_TITLE: Failed execution
        SLACK_USERNAME: Deploy Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  check_result_sonar:
    needs: sonarcloud
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Failed coverage tests
      if: ${{ needs.sonarcloud.result == 'failure' }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: sonarqube
        SLACK_COLOR: "#9e2a2b"
        #SLACK_ICON: https://someurl.com/logo.png
        SLACK_MESSAGE: "failed coverage tests"
        SLACK_TITLE: Failed execution
        SLACK_USERNAME: Deploy Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Successful coverage tests
      if: ${{ needs.sonarcloud.result == 'success' }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: sonarqube
        SLACK_COLOR: "#52FF33"
        #SLACK_ICON: https://someurl.com/logo.png
        SLACK_MESSAGE: "successful coverage tests"
        SLACK_TITLE: Successful execution
        SLACK_USERNAME: Deploy Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}